// React/src/App.tsx
import React from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import NumberBox, { NumberBoxTypes } from 'devextreme-react/number-box';
import type dxNumberBox from 'devextreme/ui/number_box';
import DxDataGrid, { DataGridTypes, Column, FilterRow } from 'devextreme-react/data-grid';
import { payments } from './data';

const nonZeroFormat = '##.######';
const zeroFormat = '0#.######';
const zeroFormatEditorOptions = {
  format: nonZeroFormat,
};
const nonZeroFormatEditorOptions = {
  format: '$ #,##0.##',
};

type CustomContentReadyEvent = NumberBoxTypes.ContentReadyEvent & {
  component: ExtendedNumberBox;
};
type ExtendedNumberBox = dxNumberBox & {
  isLoaded: boolean;
};

function onContentReady(e: CustomContentReadyEvent): void {
  if (!e.component.isLoaded) {
    e.component.isLoaded = true;
    if (e.component.option('value') === 0) { e.component.option('format', zeroFormat); }
  }
}

function NonZeroKeyDown(e: NumberBoxTypes.KeyDownEvent): void {
  const value = e.component.option('value');
  if (e.event?.key === '0' && value === null) {
    e.component.option('format', zeroFormat);
  } else if (e.event?.key === 'Backspace' && value === 0) {
    e.component.option('format', '');
  } else if (value != null && (value > -1 && value < 1)) {
    e.component.option('format', zeroFormat);
  } else {
    e.component.option('format', nonZeroFormat);
  }
}

function ZeroKeyDown(e: NumberBoxTypes.KeyDownEvent): void {
  if (e.event?.key === 'Backspace' && e.component.option('value') === 0) {
    e.component.option('format', '');
  } else {
    e.component.option('format', '$ #,##0.##');
  }
}

function onEditorPreparing(e: DataGridTypes.EditorPreparingEvent): void {
  if (e.parentType !== 'filterRow') return;
  if (e.dataField === 'PaymentId') {
    e.editorOptions.onContentReady = (args: CustomContentReadyEvent): void => {
      const editorInstance = args.component;
      if (!editorInstance.isLoaded) {
        editorInstance.isLoaded = true;
        if (editorInstance.option('value') === 0) { editorInstance.option('format', zeroFormat); }
      }
    };
    e.editorOptions.onKeyDown = (args: NumberBoxTypes.KeyDownEvent): void => {
      const editorInstance = args.component;
      const value = editorInstance.option('value');
      if (args.event?.key === '0' && value === null) {
        editorInstance.option('format', zeroFormat);
      } else if (args.event?.key === 'Backspace' && value === 0) {
        editorInstance.option('format', '');
      } else if (value != null && (value > -1 && value < 1)) {
        editorInstance.option('format', zeroFormat);
      } else {
        editorInstance.option('format', nonZeroFormat);
      }
    };
  }
  if (e.dataField === 'Amount') {
    e.editorOptions.onKeyDown = (args: NumberBoxTypes.KeyDownEvent): void => {
      const editorInstance = args.component;
      if (args.event?.key === 'Backspace' && editorInstance.option('value') === 0) {
        editorInstance.option('format', '');
      } else {
        editorInstance.option('format', '$ #,##0.##');
      }
    };
  }
}

function App(): JSX.Element {
  return (
    <div className="main">
      <NumberBox
        defaultValue={0}
        width={400}
        label="zero-based format"
        format="$ 0,###.##"
        valueChangeEvent="keyup"
        onKeyDown={ZeroKeyDown}
      />
      <NumberBox
        defaultValue={0}
        width={400}
        label="non-zero format"
        format={nonZeroFormat}
        valueChangeEvent="keyup"
        /* @ts-expect-error : a custom event type is used */
        onContentReady={onContentReady}
        onKeyDown={NonZeroKeyDown}
      />
      <DxDataGrid dataSource={payments} keyExpr="PaymentId" onEditorPreparing={onEditorPreparing} showBorders>
        <Column dataField='PaymentId' caption='Payment Id (non-zero format)' dataType='number' width={200} format={nonZeroFormat}
          editorOptions={zeroFormatEditorOptions}
        />
        <Column dataField='Amount' caption='Amount (zero-based format)' dataType='number' format="$ #,##0.##"
          editorOptions={nonZeroFormatEditorOptions}
        />
        <Column dataField='PaymentDate' dataType='date' />
        <FilterRow visible applyFilter="auto" />
      </DxDataGrid>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

import { DxNumberBoxTypes } from 'devextreme-angular/ui/number-box';
import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
import dxNumberBox from 'devextreme/ui/number_box';

import { PaymentInfo, Service } from './app.service';

type CustomContentReadyEvent = DxNumberBoxTypes.ContentReadyEvent & {
  component: ExtendedNumberBox;
};
type ExtendedNumberBox = dxNumberBox & {
  isLoaded?: boolean;
};

@Component({
  selector: 'app-root',
  providers: [Service],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],

})

export class AppComponent {
  nonZeroFormat = '##.######';

  zeroFormat = '0#.######';

  currencyFormat = '$ #,##0.##';

  zeroFormatEditorOptions;

  nonZeroFormatEditorOptions;

  dataSource: PaymentInfo[];

  constructor(service: Service) {
    this.zeroFormatEditorOptions = {
      format: this.nonZeroFormat,
    };
    this.nonZeroFormatEditorOptions = {
      format: this.currencyFormat,
    };
    this.dataSource = service.getPayments();
  }

  onContentReady = (e: CustomContentReadyEvent): void => {
    if (!e.component.isLoaded) {
      e.component.isLoaded = true;
      if (e.component.option('value') === 0) e.component.option('format', this.zeroFormat);
    }
  };

  onNonZeroKeyDown = (e: DxNumberBoxTypes.KeyDownEvent): void => {
    const value = e.component.option('value');
    if (e.event?.key === '0' && value === null) {
      e.component.option('format', this.zeroFormat);
    } else if (e.event?.key === 'Backspace' && value === 0) {
      e.component.option('format', '');
    } else if (value != null && (value > -1 && value < 1)) {
      e.component.option('format', this.zeroFormat);
    } else {
      e.component.option('format', this.nonZeroFormat);
    }
  };

  onZeroKeyDown = (e: DxNumberBoxTypes.KeyDownEvent): void => {
    if (e.event?.key === 'Backspace' && e.component.option('value') === 0) {
      e.component.option('format', '');
    } else {
      e.component.option('format', this.currencyFormat);
    }
  };

  onEditorPreparing(e: DxDataGridTypes.EditorPreparingEvent): void {
    if (e.parentType !== 'filterRow') return;
    if (e.dataField === 'PaymentId') {
      e.editorOptions.onContentReady = this.onContentReady;
      e.editorOptions.onKeyDown = this.onNonZeroKeyDown;
    }
    if (e.dataField === 'Amount') e.editorOptions.onKeyDown = this.onZeroKeyDown;
  }
}

<div class="default-style">
  <dx-number-box [width]="400" [format]="currencyFormat" valueChangeEvent="keyup" (onKeyDown)="onZeroKeyDown($event)"
    label="zero-based format">
  </dx-number-box>
  <dx-number-box [width]="400" [format]="zeroFormat" valueChangeEvent="keyup" (onContentReady)="onContentReady($event)"
    (onKeyDown)="onNonZeroKeyDown($event)" label="non-zero format">
  </dx-number-box>
  <dx-data-grid [dataSource]="dataSource" keyExpr="PaymentId" [showBorders]="true"
    (onEditorPreparing)="onEditorPreparing($event)">
    <dxi-column dataField="PaymentId" caption="Payment Id (non-zero format)" dataType="number" [width]="200"
      [format]="nonZeroFormat" [editorOptions]="nonZeroFormatEditorOptions"> </dxi-column>
    <dxi-column dataField="Amount" caption="Amount (zero-based format)" dataType="number" [width]="200"
      [format]="currencyFormat" [editorOptions]="zeroFormatEditorOptions"> </dxi-column>
    <dxi-column dataField="PaymentDate" dataType="date"> </dxi-column>
    <dxo-filter-row [visible]="true" applyFilter="auto"></dxo-filter-row>
  </dx-data-grid>
</div>
